name: Setup Bun Environment
description: Setup mise and install Bun dependencies

inputs:
  artifactory-username:
    description: Artifactory private reader username
    required: true
  artifactory-password:
    description: Artifactory private reader access token
    required: true

runs:
  using: composite
  steps:
    - uses: jdx/mise-action@2d8d4cafcbd33be2ea37d2b6f5ad595363d1f1ca # v5.1.1
      with:
        version: 2026.9.14

    - name: Install dependencies
      shell: bash
      env:
        ARTIFACTORY_PRIVATE_READER_USERNAME: ${{ inputs.artifactory-username }}
        ARTIFACTORY_PRIVATE_READER_PASSWORD: ${{ inputs.artifactory-password }}
        BUN_CONFIG_REGISTRY: https://repox.jfrog.io/artifactory/api/npm/npm/
        NPM_CONFIG_REGISTRY: https://repox.jfrog.io/artifactory/api/npm/npm/
      run: bun ci
