name: Releasability status
on:
  workflow_dispatch:
  workflow_run:
    workflows: [Build]
    types:
      - completed
    branches:
      - master

jobs:
  update_releasability_status:
    runs-on: sonar-xs
    name: Releasability status
    permissions:
      id-token: write
      statuses: write
      contents: read
    steps:
      - uses: SonarSource/gh-action_releasability/releasability-status@760079129287f6a5ae9ffcceecc5d73befdd700c # 3.3.0
        with:
          optional_checks: "Jira,CheckDependencies,CheckManifestValues"
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
