name: sonar-release

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: Version
        required: true
      dryRun:
        type: boolean
        description: Flag to enable the dry-run execution
        default: false
        required: false

jobs:
  release:
    permissions:
      id-token: write
      contents: write
    uses: SonarSource/gh-action_release/.github/workflows/main.yaml@bf4faffefea8fce5e434a3b185d2ac03fba5592c # 7.7.1
    with:
      version: ${{ inputs.version }}
      dryRun: ${{ inputs.dryRun }}
      publishToBinaries: true
      slackChannel: C02E6L5C01H # squad-devex-private
      skipJavascriptReleasabilityChecks: true
      createDraftRelease: false

  update-stable-channel:
    needs: release
    if: ${{ !inputs.dryRun }}
    runs-on: sonar-xs
    permissions:
      id-token: write # OIDC → Vault
      contents: read
    steps:
      - uses: SonarSource/ci-github-actions/update-release-channel@4402eb038c849d74631b25f8e9d58e89e983e197 # master
        with:
          version: ${{ inputs.version }}
          channel: stable
